site_name: LLaMArch
site_url: https://gpavanb1.github.io/llamarch-docs/
deploy:
  remote_branch: gh-pages
  remote_name: public-origin
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
nav:
  - Home: index.md
  - Getting Started: start.md
  - Pricing: pricing.md
  - License: license.md
  - Code Documentation:
      - Overview: overview.md
      - Common Components:
        - LLM: common/llm.md
        - LLM Embedding: common/llm_embedding.md
        - FineTuner: common/fine_tuner.md
        - Cache: common/cache.md
        - VectorDB: common/vector_db.md
        - GraphDB: common/graph_db.md
        - Base Agent: common/base_agent.md
      - Patterns:
        - Agent Swarm: patterns/agent_swarm.md
        - Knowledge Graph: patterns/knowledge_graph.md
        - Layered Caching: patterns/layered_caching.md
        - Memory Cognition: patterns/memory_cognition.md
        - Multi-Agent Feedback: patterns/multiagent_feedback.md
        - Student-Teacher: patterns/student_teacher.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            members_order: source
  

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML


extra_css: 
  - assets/docs.css